### ISSUE TITLE
Hi is this repo still supported by original author?

### ISSUE THREAD

**Issue by naterex** [raldenhoven/downloadify#10]
see subject

**Comment by jabbink** [comment]
see `README.md`

**Comment by raldenhoven** [comment]
You are correct @jabbink.

**Comment by jabbink** [comment]
@raldenhoven As I assume you won't ever update this anymore, may I suggest to just disable issues for this repo so you won't get unnecessary mails/notifications when someone again asks why this doesn't work anymore.

(https://github.com/raldenhoven/downloadify/settings -> check box for issues off -> save)

**Comment by raldenhoven** [comment]
@jabbink  Thnx will do!
