### ISSUE TITLE
Downloadify not working

### ISSUE THREAD

**Issue by faizych** [raldenhoven/downloadify#8]
I downloaded the zip file and when I try to run the test.html and click on the "SAVE TO DISK" button nothing happens.  Its just a dead button and doesn't prompt me with a dialog dox to save and doesn't show any errors.  same test html page is working on the site online but when i pull it locally it doesn't work.. any help?

**Comment by dwbfox** [comment]
Being open source is a double-edged sword I suppose. I'm sure they'll be likely to follow this repo and patch anything that comes through on the fly.
