### ISSUE TITLE
Any idea how to get this working with rtmp streams?

### ISSUE THREAD

**Issue by shillshocked** [raldenhoven/downloadify#9]
Here is a sample url:

rtmp://spjfyhfrbp9td.cloudfront.net/cfx/st/mp3:mp3/267629648d1105edb719ced42a5308fd22615ced?Expires=1400166609&Signature=BmPkPqAeJNCZfttpy2BEZ5BbJHos8XiTBX5jV-30bM0q1LNQ89WjwY~WV-kgjzKAONGPy4c0D1wG0UbIJsJ8a~XHYzKDmsKo8YIo-fOWh3OyNGK2KsCXqAZVfsyHjkbMZHwYKQR6jocDaNXaL60vvaoWuJEUGyUzcpVwyiXtvMk_&Key-Pair-Id=APKAIJ6GQLKYCDRS5HFA

**Comment by raldenhoven** [comment]
Yes, i did found a way... but not with a simple chrome plugin.

**Comment by shillshocked** [comment]
Care to elaborate?

**Comment by pcworld** [comment]
https://github.com/TooTallNate/node-spotify-web/

**Comment by raldenhoven** [comment]
@shillshocked This plugin wasn't a real hack... it was not protected, it is protected now... It is not my mission to actually break Spotify's encryption.

@pcworld Verry simply explained, it lets the Spotify player decode there file and route the actual sound to a new compressor to create an mp3.... so you are not getting the original file.
